FROM python:3.12-alpine
ENV APP_ROOT /var/www

RUN apk update \
  && apk add --no-cache bash vim openssh curl git

WORKDIR /var/www

RUN pip install --upgrade pip \
  && pip install --upgrade setuptools

COPY ./app/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "3000"]